--------------------------------------------------------
--  파일이 생성됨 - 토요일-6월-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "ONECHO"."ITEM" 
   (	"ITEM_NO" NVARCHAR2(10), 
	"ITEM_NAME" NVARCHAR2(50), 
	"ITEM_CATEGORY" NVARCHAR2(2000), 
	"KEYWORD_NO" NVARCHAR2(20), 
	"ITEM_PRICE" NUMBER, 
	"ITEM_DISCOUNT" NUMBER, 
	"ITEM_RATE" NUMBER, 
	"ITEM_STOCK" NUMBER, 
	"ITEM_DISPLAY" NVARCHAR2(2) DEFAULT 'N', 
	"ITEM_INFO" NVARCHAR2(2000), 
	"ITEM_CDATE" DATE DEFAULT SYSDATE, 
	"ITEM_UDATE" DATE DEFAULT SYSDATE, 
	"ITEM_SCOUNT" NUMBER, 
	"ITEM_MAX" NUMBER, 
	"ITEM_SALE" NVARCHAR2(2) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_NO" IS '상품번호(I1~)';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_NAME" IS '상품명';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_CATEGORY" IS '상품카테고리';
   COMMENT ON COLUMN "ONECHO"."ITEM"."KEYWORD_NO" IS '키워드번호(K1~)';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_PRICE" IS '상품가격';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_DISCOUNT" IS '할인가격';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_RATE" IS '평점';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_STOCK" IS '상품재고';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_DISPLAY" IS '전시: Y, 비전시: N';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_INFO" IS '상품설명';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_CDATE" IS '상품등록일';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_UDATE" IS '최종수정일';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_SCOUNT" IS '누적판매량';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_MAX" IS '최대구매수량';
   COMMENT ON COLUMN "ONECHO"."ITEM"."ITEM_SALE" IS '판매중: Y, 판매중지: N';
REM INSERTING into ONECHO.ITEM
SET DEFINE OFF;
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I2','문샤인','SOIL','K1',25000,24000,0,34,'Y','이름 그대로 달빛을 머금은듯한 오묘한 색이 매력적인 문샤인',to_date('20/05/22','RR/MM/DD'),to_date('20/05/22','RR/MM/DD'),8,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I3','몬스테라','SOIL','K1',27000,26000,0,21,'Y','넓은 잎이 주는 이국적인 분위기를 내는 몬스테라',to_date('20/05/23','RR/MM/DD'),to_date('20/05/23','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I4','디시디아','HANGING','K3',19500,17000,0,15,'Y','동글동글한 입사귀에 흰색 테두리가 매력적인 디시디아',to_date('20/05/24','RR/MM/DD'),to_date('20/05/24','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I5','라탄포레스트','SOIL','K1',28900,26900,0,19,'Y','스파티필름과 스노우사파이어가 라탄바구니에 담겨 이국적인 분위기를 업 ',to_date('20/05/25','RR/MM/DD'),to_date('20/05/25','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I6','스파티필름','WATER','K1',22000,21000,0,31,'Y','사계절 내내 아름다운 꽃과 함께하는 즐거움 스파티필름',to_date('20/05/26','RR/MM/DD'),to_date('20/05/26','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I7','행운목','WATER','K1',20000,17000,0,28,'Y','이산화탄소, 포름알데히드, 벤젠 등의 유해물질을 모두 흡수해주는 행운목',to_date('20/05/27','RR/MM/DD'),to_date('20/05/27','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I8','산세베리아','SOIL','K1',23500,22500,0,21,'Y','사막에 있는 선인장, 생명력 왕이라 불리는 산세베리아',to_date('20/05/28','RR/MM/DD'),to_date('20/05/28','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I9','틸란테라리움','SOIL','K3',24500,23000,0,55,'Y','지구상에서 가장 강력한 공기청정기 틸란드시아',to_date('20/05/29','RR/MM/DD'),to_date('20/05/29','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I10','스킨답서스','WATER','K1',15000,14000,0,43,'Y','환경적응력이 뛰어나 반려식물 초보자도 친구가 될 수 있는 스킨답서스',to_date('20/05/30','RR/MM/DD'),to_date('20/05/30','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I11','수경몬스테라','WATER','K1',27000,24000,0,5,'Y','정화능력이 뛰어나 새 집이나 사무실에서 각광받는 수경몬스테라',to_date('20/05/31','RR/MM/DD'),to_date('20/05/31','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I12','테이블야자','WATER','K3',22500,19500,0,7,'Y','공기정화는 물론 가습효과까지 탁월한 테이블야자',to_date('20/06/01','RR/MM/DD'),to_date('20/06/01','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I13','스노우사파이어','WATER','K1',28000,27000,0,9,'Y','부와 행운을 가져다준다는 스노우사파이어',to_date('20/06/02','RR/MM/DD'),to_date('20/06/02','RR/MM/DD'),7,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I14','이오난사','HANGING','K3',20000,16500,0,30,'Y','크기는 작지만 공기를 정화시켜주는 이오난사',to_date('20/06/03','RR/MM/DD'),to_date('20/06/03','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I15','필레아페페','WATER','K3',30000,26000,0,9,'Y','귀여운 비주얼에 걸맞는 귀여운 이름, 필레아페페',to_date('20/06/04','RR/MM/DD'),to_date('20/06/04','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I16','스투키','SOIL','K1',21500,19500,0,11,'Y','미국 NASA에서도 인증한 공기정화 능력을 가진 스투키',to_date('20/06/05','RR/MM/DD'),to_date('20/06/05','RR/MM/DD'),20,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I17','마리모','WATER','K2',25000,22500,0,20,'Y','기분이 좋을땐 물 위를 둥둥, 보기만 해도 행복해지는 귀여운 마리모',to_date('20/06/06','RR/MM/DD'),to_date('20/06/06','RR/MM/DD'),19,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) values ('I1','야자수염틸란드시아','HANGING','K3',26500,25000,0,28,'Y','집에 싱그러움을 더해줄 뿐 아니라 공기정화 능력도 뛰어난 야자수염틸란드시아',to_date('20/05/21','RR/MM/DD'),to_date('20/05/21','RR/MM/DD'),13,10,'Y');
--------------------------------------------------------
--  DDL for Index PK_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ONECHO"."PK_ITEM" ON "ONECHO"."ITEM" ("ITEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "ONECHO"."ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY ("ITEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ONECHO"."ITEM" ADD CONSTRAINT "CK_ITEM_SALE" CHECK (item_sale in('Y', 'N')) ENABLE;
  ALTER TABLE "ONECHO"."ITEM" ADD CONSTRAINT "CK_ITEM_DISPLAY" CHECK (item_display in('Y', 'N')) ENABLE;
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_MAX" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_SCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_CDATE" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_INFO" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_STOCK" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("KEYWORD_NO" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ONECHO"."ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
